luan/nvim

- include/lint.vim
This linter seems to catch more potential errors than the standard
`golint`. For example, if you ignore the return value of a function, it
will report an error, whereas `golint` does not.
https://github.com/golangci/golangci-lint
> Add support for golangci-lint

- coc-settings.json
Following the advice [here](https://github.com/neoclide/coc-snippets#faq) we decided it will be good to expand the snippets vocabulary.
> Make coc-snippets use snippets defined in vim-go

- include/basic.vim
With these changes, a user may `set list` to make their whitespace
visible. I would probably leave this on by default for myself but I can
understand it being distracting for others.
Again this isn't on by default tho
> Introduce useful defaults for listmode/visible whitespace

- README.md
- doc/migrating-from-legacy.txt
- doc/tags
As [discussed here](https://github.com/luan/nvim/pull/25#issuecomment-579352864), this is a first stab at a help file for folks who want to know what's changed as they move from [legacy-vimfiles](https://github.com/luan/vimfiles) to this config.
There's a broken link in `README.md` in this PR, which I hope will un-break itself if the PR is merged.
> Add a help file for migrating from legacy-vimfiles

- keyboard.vim
The CR seems to be automatically added when running commands this way.
> Removed CR from menu commands

- keyboard.vim
It was giving an error whenever I tried to use it; this fixes that
error. It also no longer skips go/js files so it can be used for go and
js projects as well.
> Fix starscope call

- include/syntax.vim
This command is useful when creating new color schemes. Running `:SyntaxGroup` will display the syntax highlighting group of the text element under the cursor, which can then be targeted and styled from a color scheme.
> Add SyntaxGroup helper command

- coc-settings.json
This enables actual code navigation stuff like go-to definition, find references, and symbol searching for ruby projects.
This would be very helpful pls. Idk if we have to configure other things too though? Like that `include/coc.vim` file? Tested that all the above features worked with this change only
> Update coc-solargraph config to do more things

- plug.vim
This is the plugin [recommended by thoughtbot](https://thoughtbot.com/blog/modern-typescript-and-react-development-in-vim) for highlighting `tsx` files.
Also, hi, I miss y'all, hope life is good.
> Add plugin for highlighting tsx files

- include/basic.vim
resolves #39
This was adding newlines to many files where they shouldn't be, breaking certain kinds of bash scripts. Enforcing line length should be the responsibility of a language-specific linter, not a global rule for the editor.
> remove textwidth limitation

- keyboard.vim
Assuming that coc is working, it seems like it's a more reliable source
than to rely on Universal Ctags (the default).
[1]: https://github.com/liuchengxu/vim-clap/blob/695363e4310252fba8139970e16b76045f14781c/doc/clap-support.txt#L159
> Use coc for Clap tags executive [1]

- plug.vim
The README on https://github.com/mxw/vim-jsx mentions that it is deprecated 
and points to https://github.com/MaxMEllon/vim-jsx-pretty as a proposed alternative.
> Update jsx plugin

- update.vim
On Ubuntu fd-find's binary has been renamed from [fd` to `fdfind ](https://github.com/sharkdp/fd#on-ubuntu)leading to me and @sethboyles always seeing a dependency warning when we launch nvim, we made this change to not post the missing dependency warning as it will check for fdfind if fd is not present.  We checked Vim-Clap using :Clap after talking to [Luan in cloudfoundry slack](https://cloudfoundry.slack.com/archives/C0YVC7K8S/p1612994834175500) and saw it working with our change just fine.
Let us know if you have any questions :D!
Thanks!
Jenna and Seth
> Check for fdfind as well if fd is not present

- include/coc.vim
I was seeing some weird behavior where when I'd save a file and it added/changed imports that random parts of my Go file would get deleted/rearranged.
I don't know why this fixes it, but this is how it's recommended to do this [on the coc-go README](https://github.com/josa42/coc-go#examples)
> Fix organizeImport

- lua/plugins/completion.lua
Without this change, it fails to go back to the previous placeholder.
> Update vsnip to jump to previous placeholder

- lua/globals.lua
Add support to users to optionally add their custom snippets without messing with the `~/.vsnip/` directory and having file links everywhere
> Add the ability for users to add their snippets

- lua/plugins/lualine.lua
Corrects the following errors:
> ```
> lualine: There are some issues with your config. Run :LualineNotices for details
> ```
> Diagnostics source `nvim_lsp` has been deprecated in favour of `nvim_diagnostic`.
> nvim_diagnostic shows diagnostics from neovim's diagnostics api
> while nvim_lsp used to only show lsp diagnostics.
> 
> You've something like this your config.
>  ```lua
>   {'diagnostics', sources = {'nvim_lsp'}}
>  ```
> It needs to be updated to:
>  ```lua
>   {'diagnostics', sources = {'nvim_diagnostic'}}
> ```
> Replaces nvim_lsp with nvim_diagnostic (#75)

- lua/plugins/completion.lua
This turns out to be really annoying, I'm typing stuff and hit enter expecting a carriage return and get some random completion inserted instead
Reverts luan/nvim#84
> Revert "Allow enter key to accept completion"

- lua/plugins/truezen.lua
This was causing a error message every time vim loads up, as it couldn't
find the gitsigns.nvim anymore - which was replaced by vgit.
> Disable gitsigns integration as it's no longer available

- lua/lang.lua
update_capabilities was deprecated, per this PR:
https://github.com/hrsh7th/cmp-nvim-lsp/pull/35/files
switched to default_capabilities()
Co-authored-by: Christian Ang <christian.ang@outlook.com>
> Update cmp-nvim-lsp config for deprecation

- lua/plugins/lir.lua
`devicons_enable` is deprecated and we should use `devicons.enable` instead.
> Fix lir devicons deprecation warning
